# Generated by Django 3.2.2 on 2021-12-19 17:57

import core.accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=core.accounts.models.LowercaseCharField(error_messages={'unique': 'This username is not available, please try another one.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=300, unique=True, verbose_name='username'),
        ),
    ]
