# Generated by Django 3.2.2 on 2022-01-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover_pic',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
