# Generated by Django 3.2.2 on 2022-01-05 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_cover_pic"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="num_posts",
            new_name="posts",
        ),
    ]
