# Generated by Django 4.0 on 2021-12-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='revenue',
            field=models.FloatField(default=0.0),
        ),
    ]
