# Generated by Django 3.2.2 on 2021-12-19 10:58

from django.db import migrations, models
import markdownfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(blank=True, max_length=30, null=True)),
                ('title', models.CharField(max_length=140)),
                ('cover_image', models.CharField(blank=True, max_length=2000, null=True)),
                ('text', markdownfield.models.MarkdownField(rendered_field='text_rendered', use_editor=False)),
                ('text_rendered', markdownfield.models.RenderedMarkdownField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
