# Generated by Django 3.2.2 on 2021-12-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default="Author was too 'cool' to follow markdown guidelines 🙄", max_length=140),
        ),
    ]
