# Generated by Django 3.2.2 on 2022-01-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, default="Author was too 'cool' to follow markdown guidelines 🙄", max_length=140),
        ),
    ]
