# Generated by Django 3.2.2 on 2022-01-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='followers',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
