# Generated by Django 3.2.2 on 2021-12-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
