# Generated by Django 3.2.2 on 2022-01-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_tag_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
