# Generated by Django 3.2.2 on 2022-01-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_tag_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='posts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
