# Generated by Django 3.2.2 on 2022-01-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_tag_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='accent_colour',
            field=models.CharField(blank=True, max_length=2000, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='cover_image',
            field=models.CharField(blank=True, max_length=2000, null=True, unique=True),
        ),
    ]
