# Generated by Django 3.2.2 on 2021-12-31 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='update',
            old_name='content',
            new_name='title',
        ),
    ]
